name: Trigger Render Deploy

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  ping-render:
    runs-on: ubuntu-latest    
    steps:
      - name: Call Render Deploy Hook
        run: |
          curl https://edubox-m2z5.onrender.com/